import type { DashboardDevice } from "../server/devices";

export const statusLabels = { connected: "Connected", recently_seen: "Recently seen", offline: "Offline", stale: "Stale", revoked: "Revoked", unknown: "Unknown" } as const;
export const statusRank = { connected: 0, recently_seen: 1, offline: 2, stale: 3, revoked: 4, unknown: 5 } as const;
export type SortMode = "default" | "name" | "lastSeen" | "created" | "clientVersion" | "email" | "activeRegistrations";
export type Filters = { query: string; os: string; status: string; profile: string };
const safe = (value: unknown) => value == null ? "" : String(value);
export const activeCount = (d: DashboardDevice) => d.registrations.filter((r) => r.status === "active").length;
export const firstEmail = (d: DashboardDevice) => d.lastUser?.email || d.registrations.find((r) => r.user?.email)?.user?.email;
export function osName(value?: string) { const v = safe(value).toLowerCase(); if (v.includes("windows")) return "Windows"; if (v.includes("mac") || v.includes("darwin")) return "macOS"; if (v.includes("linux")) return "Linux"; if (v.includes("android")) return "Android"; if (v.includes("ios") || v.includes("iphone") || v.includes("ipad")) return "iOS"; if (v.includes("chrome")) return "ChromeOS"; return "Unknown OS"; }
export const profileName = (p?: DashboardDevice["profile"]) => p ? p.name || p.id || "Unknown profile" : "";
export function badges(d: DashboardDevice) { const v: string[] = []; if (d.registrations.length > 1) v.push("Multiple registrations"); if (d.registrations.some((r) => r.keyType?.toLowerCase().includes("service"))) v.push("Service token"); if (d.status === "revoked") v.push("Revoked"); if (d.registrations.length && activeCount(d) === 0) v.push("No active registration"); if (d.status === "stale") v.push("Stale"); if (!d.osVersion && !d.deviceType) v.push("Unknown OS"); if (d.profile?.deleted || d.registrations.some((r) => r.profile?.deleted)) v.push("Profile deleted"); return v; }
export function searchBlob(d: DashboardDevice) { return [d.id,d.name,d.dnsHostname,d.deviceType,d.osVersion,d.osVersionExtra,d.clientVersion,d.lastUser?.name,d.lastUser?.email,profileName(d.profile),...d.registrations.flatMap((r) => [r.id,r.user?.name,r.user?.email,r.virtualIpv4,r.virtualIpv6,r.tunnelType,r.keyType,profileName(r.profile)])].filter(Boolean).join(" ").toLowerCase(); }
export const dateValue = (v?: string) => { const n = Date.parse(v || ""); return Number.isFinite(n) ? n : 0; };
export function sortDevices(devices: DashboardDevice[], mode: SortMode) { return [...devices].sort((a,b) => { if (mode === "name") return safe(a.name).localeCompare(safe(b.name)); if (mode === "lastSeen") return dateValue(b.lastSeenAt)-dateValue(a.lastSeenAt); if (mode === "created") return dateValue(b.createdAt)-dateValue(a.createdAt); if (mode === "clientVersion") return safe(a.clientVersion).localeCompare(safe(b.clientVersion), undefined, {numeric:true}); if (mode === "email") return safe(firstEmail(a)).localeCompare(safe(firstEmail(b))); if (mode === "activeRegistrations") return activeCount(b)-activeCount(a); return (statusRank[a.status] ?? 5)-(statusRank[b.status] ?? 5) || safe(a.name).localeCompare(safe(b.name)); }); }
export function filterDevices(devices: DashboardDevice[], f: Filters) { const q=f.query.trim().toLowerCase(); return devices.filter((d) => (!q || searchBlob(d).includes(q)) && (!f.os || osName(d.deviceType || d.osVersion) === f.os) && (!f.status || statusLabels[d.status] === f.status) && (!f.profile || profileName(d.profile) === f.profile)); }
export function relativeTime(v?: string) { if (!v) return "Unknown"; const s=Math.max(0,Math.floor((Date.now()-dateValue(v))/1000)); if(s<60)return "Just now"; const m=Math.floor(s/60); if(m<60)return `${m} minutes ago`; const h=Math.floor(m/60); if(h<24)return `${h} hours ago`; return formatShort(v); }
export const formatShort = (v: string) => new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
export const formatAbsolute = (v: string) => new Intl.DateTimeFormat(undefined,{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",timeZoneName:"short"}).format(new Date(v));
export const formatMaybeDate = (v?: string | null) => v ? formatAbsolute(v) : "—";
